### PR TITLE
feat: add support for camunda variable escaping extension

### LINKED ISSUE #36: Support for camunda extension "Escape variable names"?
### Is your feature request related to a problem? Please describe

Hi,
thanks for maintaining this great grammar for feel.
I'm wondering if it should also support escaped variables via backticks as defined in the feel guides: https://docs.camunda.io/docs/components/modeler/feel/language-guide/feel-variables/#escape-variable-names

I know it's marked as camunda extension but should the tokenizer also detect these as `VariableName`? 
Right now it just errors. This also happens in the camunda modeler.

### Describe the solution you'd like

```
`first name`

`tracking-id`

order.`total price`
```

should output VariableName tokens without errors.

### Describe alternatives you've considered

Fork this library and add support for the camunda extension which might not be intended to be included in the base grammar.

### PR DESCRIPTION
**Pull request by makepanic**
### Which issue does this PR address?

Closes #36

### CODE REVIEW

**Comment by makepanic** [comment]
I'm not sure if it's really a good idea to let the whole back tick content be a VariableName token or if it's better to use a separate token.

**Comment by nikku** [comment]
Cf. https://github.com/nikku/lezer-feel/issues/36#issuecomment-2301687002 and previous comments. I think you want to declare it as a token extension. I'd be fine to accept a PR that implements this as a "camunda" dialect.

**Comment by nikku** [comment]
> I'm not sure if it's really a good idea to let the whole back tick content be a VariableName

I think the backtick content should be an `Identifier`, so grammar wise `VariableName` is composed in the same way.

**Comment by nikku** [comment]
The `lezer/javascript` grammar has some good pointers how to work with [lezer dialects](https://lezer.codemirror.net/docs/guide/#dialects):

https://github.com/lezer-parser/javascript/blob/main/src/javascript.grammar

**Comment by makepanic** [comment]
Thanks for the feedback.
I've updated the grammar with the camunda dialect and adjusted the test to set the dialect where needed.

**Comment by makepanic** [comment]
I'm not sure if that's what you meant but I've updated the grammar to extract a new BacktickIdentifier which is used in the VariableName

**Comment by nikku** [comment]
Thanks, great contribution. Merged with minor adjustments (cf. https://github.com/nikku/lezer-feel/pull/37/commits/2e8da37091772f9c9a05027421809690375f9944).

**Comment by nikku** [comment]
Released as https://github.com/nikku/lezer-feel/releases/tag/v1.3.0.

**Pull request merged**
